In [60]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from copy import copy

In [107]:
class BassBoost():
    
    def __init__(self, max_depth, max_iter=5):
        self.trees = []
        self.max_depth = max_depth
        self.max_iter = max_iter
        
    def bias_pred(self, X, y):
        pred = np.zeros(X.shape[0])
        
        for tree in range(len(self.trees)):
            pred += tree.predict(X)
        
        return pred
    
    def _calc_grad(self, y, pred):
        return 2 * (pred - y)
        
         
    def fit(self, X_index, X_bias, y):
        target = y.copy()
        
        for i in range(self.max_iter):
            linear = LinearRegression().fit(X_index, target)
            self.betas = linear.coef_
            self.intercept = linear.intercept_
            
            grads = self._calc_grad(y, X_index @ self.betas + self.intercept)
            
            tree = DecisionTreeRegressor(max_depth=self.max_depth, random_state=999).fit(X_bias, grads)
            self.trees.append(copy(tree))
            target -= tree.predict(X_bias)
            
        return target
        
    def predict(self, X, y, decompose=False):
        
        pass
        

In [108]:
from sklearn.datasets import make_regression

X, y, coef = make_regression(n_samples=100, n_features=4, n_informative=10,
                             coef=True, random_state=999, noise=30, bias=1)

In [109]:
coef

array([57.78162828, 22.70630251, 32.46204896,  3.1093743 ])

In [110]:
LinearRegression().fit(X, y).coef_

array([57.06746369, 21.24365103, 33.42935924,  4.0208379 ])

In [111]:
Bass = BassBoost(max_depth=3, max_iter=30)

Bass.fit(X[:, :-1], X[:, -1:].reshape(-1, 1), y)

array([ 2677.22337433,   862.50699483,  -209.36131819,   -91.87127577,
         232.10844751,  -643.00780146,   303.22504785,   -53.78735921,
        -103.29046987,    -4.03622718,  1079.00482932,  -582.16491057,
         -57.41699203,  -640.52757669,  -633.07896622,   -67.45507388,
        1028.05448551,   314.26191751,  -450.5304201 ,  -556.91775608,
         -62.53113074,  2866.51014645,   281.54712505,   232.91010889,
         330.8646427 ,  -384.17615709,  1042.00206745,  -885.68165125,
       -1094.00670548,  -424.56569872,  -128.39774285,  -875.80336156,
         391.69853959,    91.10317621,   298.31079872,  -317.54679376,
        -474.34456342,   268.87869301,  -439.40109318,  -528.86411997,
        -379.5060661 ,  -680.10014353,  -524.41034216,  2644.4377554 ,
        -587.59831668,  -693.52477781,  1117.72623086,  -567.29017781,
         120.94978409,  1060.50976809,   349.08761814,  -517.00654136,
        -525.17341726,  -420.7563865 ,   296.70875342,   -54.3707912 ,
      

In [112]:
Bass.betas

array([57.36563229, 21.86987763, 28.69370901])

In [113]:
LinearRegression().fit(X, y).coef_


array([57.06746369, 21.24365103, 33.42935924,  4.0208379 ])